token:
  secret: "my-secret-key-must-be-at-least-256-bits-long-and-secure"
  access-expiration: 3600000  # 1시간
  refresh-expiration: 604800000 # 7일

spring:
  data:
    redis:
      host: localhost
      port: 6379

app:
  upload:
    base-path: uploads
    max-file-size: 5242880 # 5MB
    allowed-types: jpg,jpeg,png,webp
    thumbnail-size: 200
    profile-size: 800